<?php
/**
 * Created by PhpStorm.
 * User: Promise tan
 * Date: 2017/1/12
 * Time: 18:48
 */

return [

    'Audit' => [
        'yo_audit_additional' => [
            'user_key' => '',
            'audit_type' => '',
            'audit_type_text' => '',
            'bank_income' => '',
            'know_about' => '',
            'know_about_text' => '',
            'audit_phone' => '',
            'audit_phone_text' => '',
            'has_credit_card' => '',
            'credit_quota' => '',
            'audit_wechat_num' => '',
            'housing_status' => '',
            'has_car' => '',
            'car_price' => '',
            'family_kwnoable' => '',
            'family_num' => '',
            'audit_gps_address' => '',
            'audit_net_address' => '',
            'audit_num' => '',
            'audit_time' => '',
        ],
        'yo_audit_assist' => [
            'user_key' => '',
            'family_address_real' => '',
            'company_address_real' => '',
            'is_live_with_family' => '',
            'is_accompany' => '',
            'accompany_num' => '',
            'is_accompany_apply' => '',
            'accompany_relationship' => '',
            'accompany_relationship_text' => '',
            'accompany_sex' => '',
            'data_truth' => '',
            'is_bad_habit' => '',
            'is_cheat' => '',
            'is_follow_by_rate' => '',
            'is_overdue' => '',
            'is_carry_bank_card' => '',
            'company_info_real' => '',
            'address_info_real' => '',
            'forecast_comprehensive_income' => '',
            'custom_level' => '',
            'is_check_original' => '',
            'compare_result' => '',
            'is_data_cheat' => '',
            'is_identity_match' => '',
            'is_abnormal_behavior' => '',
            'is_update_address' => '',
            'is_check_bankincome' => '',
            'is_abnormal_with_company' => '',
            'is_know_about_company' => '',
            'add_qq_or_wechat' => '',
            'has_apply_product' => '',
            'has_apply_bussiness' => '',
            'has_settle' => '',
            'is_overdue_three_months' => '',
            'live_time' => '',
            'is_immediate_family_live' => '',
            'is_custom_info_match' => '',
            'apply_reason' => '',
            'apply_reason_text' => '',
            'remark' => '',
        ],
        'yo_audit_pic' => [
            'user_key' => '',
            'url' => '',
            'type' => '',
            'filename' => '',
        ],
    ],

    'Trial' => [
        'yo_trial_company' => [
            'user_key' => '',
            'company_name' => '',
            'company_category' => '',
            'company_properties' => '',
            'company_district' => '',
            'company_address' => '',
            'company_department' => '',
            'company_position' => '',
            'company_phone' => '',
            'company_email' => '',
            'monthly_income' => '',
            'length_of_employment' => '',
            'colleague_name' => '',
            'colleague_mobile' => '',
        ],
        'yo_customer_info' => [
            'user_key' => '',
            'mobile' => '',
            'real_name' => '',
            'cert_no' => '',
            'cert_valid_date' => '',
            'cert_city' => '',
            'cert_address' => '',
            'bank_card' => '',
            'bank_name' => '',
            'bank_city' => '',
            'branch_name' => '',
            'branch_mobile' => '',
            'bank_auth_result' => '',
            'wechat_num' => '',
            'wechat_name' => '',
            'qq_num' => '',
            'birthday' => '',
            'email' => '',
            'information_type' => '',
            'custom_type' => '',
            'education_level' => '',
            'audit_address' => '',
            'audit_amount' => '',
        ],
        'yo_trial_family' => [
            'user_key' => '',
            'is_married' => '',
            'immediate_name' => '',
            'immediate_relationship' => '',
            'immediate_mobile' => '',
            'family_city' => '',
            'family_address' => '',
        ],
        'yo_trial_mobile' => [
            'user_key' => '',
            'ip' => '',
            'imei' => '',
            'phone_type' => '',
            'gps_msg' => '',
            'gps_address' => '',
            'is_root' => '',
            'app_version' => '',
            'system_version' => '',
            'mac_address' => '',
            'wifi' => '',
            'wifi_mac_address' => '',
            'app_num' => '',
            'finance_app_num' => '',
        ],
        'yo_trial_action' => [
            'user_key' => '',
            'enter_auth_page_time' => '',
            'leave_auth_page_time' => '',
            'focus_cert_wg_time' => '',
            'unfocus_cert_wg_time' => '',
            'focus_vcode_wg_time' => '',
            'unfocus_vcode_wg_time' => '',
            'focus_cert_wg_num' => '',
            'focus_card_wg_num' => '',
            'focus_phone_wg_num' => '',
            'start_home_info_time' => '',
            'end_home_info_time' => '',
            'start_work_info_time' => '',
            'end_work_info_time' => '',
            'fp_try_cnt' => '',
            'period_try_cnt' => '',
            'loan_amt_try_cnt' => '',
            'cert_pic1_upload_time' => '',
            'cert_pic2_upload_time' => '',
        ],
        'yo_trial_additional_info' => [
            'user_key' => '',
            'channel' => '',
            'product_name' => '',
            'product_code' => '',
            'amount' => '',
            'periods' => '',
            'description' => '',
            'loan_purpose' => '',
            'scan_product_num' => '',
            'danger_level' => '',
            'business_type' => '',
            'is_wifi' => '',
            'is_gsm' => '',
        ],
        'yo_trial_auth' => [
            'user_key' => '',
            'fr_idcard_vivo_score' => '',
            'fr_nciic_vivo_score' => '',
            'fr_idcard_nciic_score' => '',
            'vivo_score' => '',
            'fr_start_time' => '',
            'fr_end_time' => '',
            'fr_fail_cnt' => '',
            'cert_valid_score' => '',
        ],
        'yo_trial_pic' => [
            'user_key' => '',
            'url' => '',
            'type' => '',
            'filename' => '',
        ]
    ]
];